### ISSUE TITLE
Support for nativescript 4.0

### ISSUE THREAD

**Issue by anuragd7** [VideoSpike/nativescript-web-image-cache#43]
Hi 
Is support for nativescript 4 coming anytime soon?

**Comment by bathejasumeet** [comment]
Yes, will work on it, thanks for pointing it out

**Comment by bathejasumeet** [comment]
would get it done by next week, hope that is okay.

**Comment by anuragd7** [comment]
Thanks. That would be great.

**Comment by cryptonator000** [comment]
any update on this?

**Comment by bathejasumeet** [comment]
Hi, what is the exact error that you are getting and on which platform ? I was able to test the plugin and it worked fine on both android and iOS on ns 4.1 both js and angular projects. If you can provide a stack trace, I might be able to look into the issue better.

**Comment by dianikol** [comment]
There was an error for me that it required `'SDWebImage', '~> 4.0'` instead of the one in the default Pod file for ios, If I update the pod file manually it seems the build gets done correctly,

Another thing is that in the package.json the dependencies are for ns v3?  Is this right??

**Comment by NL33** [comment]
Updating SDWebImage manually did not work for me--so the plugin is not working with ns V4. There is a forum discussion on this that cites errors:
"NSCocoaErrorDomain Code=3840 "No value."
and
"/ios/Pods/SDWebImage/SDWebImage/SDWebImageCompat.h:56:39: warning: this block declaration is not a prototype [-Wstrict-prototypes]"

Forum: https://discourse.nativescript.org/t/speed-up-remote-image-load/6376/11

**Comment by bathejasumeet** [comment]
@dianikol , changed the peer dependencies, nativescript key specifies the minimum platform which is 3.0.0. Just re-tested the plugin on NS 4.1.0 on both android and iOS, worked. Could not reproduce the warning/error with SDWebImageCache version. 
@NL33 Regarding the forum you pointed to, I did implement in one of my previous apps clearing of cache  after 7 days to pull new refreshed images. Used application-settings to store the time since epoch and compared.
If anybody of you can share the repository you are working on that causes the error, maybe I could debug and fix. The plugin seems to work fine on NS 4.1 on my machine both ang+webpack and vanilla JS.

**Comment by dianikol** [comment]
I did the update but the error keeps coming up. For me maybe something is wrong with my setup. I'll post my error I got from terminal If you have any idea.

```
[!] CocoaPods could not find compatible versions for pod "SDWebImage":
  In Podfile:
    SDWebImage (~> 3.7.6)

    SDWebImage (~> 4.0)
Unable to apply changes on device: 7d84888d0839b9bf339dd701548dae037b818893. Error is: Command pod failed with exit code 1 Error output: 
 
[!] Automatically assigning platform `ios` with version `8.0` on target `YourApp` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] There are duplicate dependencies on `SDWebImage` in `Podfile`:

- SDWebImage (~> 4.0)
- SDWebImage (~> 3.7.6)
```
And I said earlier if I modify the Pod file of the plugin to 4.0 it works.

Thank you

**Comment by anuragd7** [comment]
Thanks. Can confirm that this is working with NS 4. Closing the issue.
